export const ERROR_OCCURS = "ERROR_OCCURS";
export const SUCCESS_OCCURS = "SUCCESS_OCCURS";
export const LOAD_ACCOUNT_SUCCESS= "LOAD_ACCOUNT_SUCCESS";
export const LOAD_EIRBMON_SUCCESS= "LOAD_EIRBMON_SUCCESS";
export const INFORMATION_BLOCKCHAIN = 'INFORMATION_BLOCKCHAIN';
export const GET_NEW_PUSHER_ID = 'GET_NEW_PUSHER_ID';
