export const ERROR_OCCURS = "ERROR_OCCURS";
export const SUCCESS_OCCURS = "SUCCESS_OCCURS";
export const LOAD_ACCOUNT_SUCCESS= "LOAD_ACCOUNT_SUCCESS";
export const LOAD_EIRBMON_SUCCESS= "LOAD_EIRBMON_SUCCESS";
